commit further changes missing from last commit

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -3,9 +3,7 @@
 export DH_VERBOSE=1
 export DEB_BUILD_HARDENING=1
 
-PACKAGE=mysql-cluster-7.1
-
-include /usr/share/dpatch/dpatch.make
+PACKAGE=mysql-cluster-7.2
 
 TMP=$(CURDIR)/debian/tmp/
 
@@ -15,11 +13,16 @@ DEB_BUILD_GNU_TYPE ?= $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
 DEB_HOST_GNU_TYPE  ?= $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
 DEBVERSION = $(shell dpkg-parsechangelog | awk '/^Version: / { print $$2 }' | sed 's/^.*-//' )
 
+#export MYSQL_BUILD_CC=$(DEB_HOST_GNU_TYPE)-gcc-4.5
+#export MYSQL_BUILD_CXX=$(DEB_HOST_GNU_TYPE)-g++-4.5
+
 DEB_SOURCE_PACKAGE ?= $(strip $(shell egrep '^Source: ' debian/control | cut -f 2 -d ':'))
 DEB_VERSION ?= $(shell dpkg-parsechangelog | egrep '^Version:' | cut -f 2 -d ' ')
 DEB_NOEPOCH_VERSION ?= $(shell echo $(DEB_VERSION) | cut -d: -f2-)
 DEB_UPSTREAM_VERSION ?= $(shell echo $(DEB_NOEPOCH_VERSION) | sed 's/-[^-]*$$//')
 DEB_UPSTREAM_VERSION_MAJOR_MINOR := $(shell echo $(DEB_UPSTREAM_VERSION) | sed -r -n 's/^([0-9]+\.[0-9]+).*/\1/p')
+
+EXPORTED_SOURCE_TARBALL = debian/mysql-cluster-source-7.2.tar.gz
 
 DISTRIBUTION = $(shell lsb_release -i -s)
 
@@ -37,7 +40,7 @@ endif
 
 USE_ASSEMBLER=--enable-assembler 
 
-ifneq (,$(filter $(ARCH), amd64 i386 ia64))
+ifneq (,$(filter $(ARCH), amd64 i386))
     TESTSUITE_FAIL_CMD=exit 1
 else
     TESTSUITE_FAIL_CMD=true
@@ -51,12 +54,12 @@ builddir = $(if $(findstring -pic,$@),$(BUILDDIR_PIC),$(BUILDDIR))
 # so it is disabled by default although, according to MySQL, it brings >10%
 # performance gain if enabled. See #299382.
 ifeq ($(STATIC_MYSQLD), 1)
-    USE_STATIC_MYSQLD=--with-mysqld-ldflags=-all-static
+    USE_STATIC_MYSQLD=WITH_MYSQLD_LDFLAGS=-all-static
 endif
 		
 
 configure-stamp-pic: FORCE_FPIC_CFLAGS=-fPIC
-configure-stamp-pic: FORCE_FPIC=--with-pic --with-lib-ccflags="-fPIC"
+configure-stamp-pic: FORCE_FPIC=-DWITH_PIC=On -DINSTALL_LIBDIR=lib/mysql
 
 configure: patch configure-stamp
 configure-pic: patch configure-stamp-pic
@@ -69,66 +72,61 @@ ifneq ($(ARCH_OS),hurd)
 endif
 
 	# TODO fix these build problems: some files don't get copied to builddir
-	mkdir -p builddir/storage/ndb/src/kernel/vm
-	cp storage/ndb/src/kernel/vm/mt-asm.h builddir/storage/ndb/src/kernel/vm
+	#mkdir -p builddir/storage/ndb/src/kernel/vm
+	#cp storage/ndb/src/kernel/vm/mt-asm.h builddir/storage/ndb/src/kernel/vm
 	# TODO --end--
 
 	( test -d $(builddir) || mkdir $(builddir) ) && cd $(builddir) && \
 	sh -c  'PATH=$${MYSQL_BUILD_PATH:-"/bin:/usr/bin"} \
-	    	VERBOSE=1 \
 	    	CC=$${MYSQL_BUILD_CC:-gcc} \
-		CFLAGS=$${MYSQL_BUILD_CFLAGS:-"-O3 -DBIG_JOINS=1 ${FORCE_FPIC_CFLAGS} -fno-strict-aliasing"} \
+		CFLAGS=$${MYSQL_BUILD_CFLAGS:-"-O2 -DBIG_JOINS=1 ${FORCE_FPIC_CFLAGS} -fno-strict-aliasing"} \
 	    	CXX=$${MYSQL_BUILD_CXX:-g++} \
-	    	CXXFLAGS=$${MYSQL_BUILD_CXXFLAGS:-"-O3 -DBIG_JOINS=1 -felide-constructors -fno-exceptions -fno-rtti ${FORCE_FPIC_CFLAGS}"} \
-	    ../configure \
+	    	CXXFLAGS=$${MYSQL_BUILD_CXXFLAGS:-"-O3 -DBIG_JOINS=1 -felide-constructors -fno-exceptions -fno-rtti ${FORCE_FPIC_CFLAGS} -fno-strict-aliasing"} \
+	    cmake \
 		--build=${DEB_BUILD_GNU_TYPE} \
-		--host=${DEB_HOST_GNU_TYPE} \
+	        --host=${DEB_HOST_GNU_TYPE} \
+	        \
+	        -DINSTALL_LAYOUT=RPM \
+	        -DCMAKE_INSTALL_PREFIX=/usr \
+		-DINSTALL_SBINDIR=/usr/sbin \
+	        -DINSTALL_LIBDIR=lib \
+	        -DINSTALL_PLUGINDIR=lib/mysql/plugin \
+		--datadir=/usr/share \
+		-DMYSQL_DATADIR=/var/lib/mysql \
+		-DINSTALL_INCLUDEDIR=/usr/include/mysql \
+		--infodir=/usr/share/info \
+		--mandir=/usr/share/man \
 		\
-		--prefix=/usr \
-	        --exec-prefix=/usr \
-	        --libexecdir=/usr/sbin \
-	        --datadir=/usr/share \
-	        --localstatedir=/var/lib/mysql \
-	        --includedir=/usr/include \
-	        --infodir=/usr/share/info \
-	        --mandir=/usr/share/man \
+		-DMYSQL_SERVER_SUFFIX="-$(DEBVERSION)" \
+	        -DWITH_COMMENT="($(DISTRIBUTION))" \
+	        -DSYSTEM_TYPE="debian-linux-gnu" \
 		\
-		--with-server-suffix="-$(DEBVERSION)" \
-		--with-comment="($(DISTRIBUTION))" \
-		--with-system-type="debian-linux-gnu" \
+		-DDISABLE_SHARED=Off \
 		\
-		--enable-shared \
-		--enable-static \
-		--enable-thread-safe-client \
+		-DTHREAD_SAFE_CLIENT=On \
 	        $(USE_ASSEMBLER) \
-		--enable-local-infile \
+		-DENABLED_LOCAL_INFILE=On \
 		$(FORCE_FPIC) \
-		--with-fast-mutexes \
-                --with-big-tables \
-		--with-unix-socket-path=/var/run/mysqld/mysqld.sock \
-	       	--with-mysqld-user=mysql \
-		--with-libwrap \
-		--without-readline \
+		-DWITH_FAST_MUTEXES=On \
+	        -DBIG_TABLES=On \
+		-DMYSQL_UNIX_ADDR=/var/run/mysqld/mysqld.sock \
+	       	-DMYSQL_USER=mysql \
+		-DWITH_LIBWRAP=On \
+		-DWITH_READLINE=Off \
 		$(USE_STATIC_MYSQLD) \
-		--with-ssl \
-	    	--without-docs \
-		--with-extra-charsets=all \
-		--with-plugins=max \
+		-DWITH_SSL=bundled \
+		-DWITH_EXTRA_CHARSETS=all \
+		-DWITH_MAX=On \
 		\
-		--without-ndb-sci \
-		--without-ndb-test \
-		--without-ndb-docs \
+		-DHAVE_NDB_SCI=Off \
+		-DWITH_NDB_TEST=Off \
+		-DWITH_NDBMTD=On \
 		\
-		--with-embedded-server \
-		--with-embedded-privilege-control'
-		
-	#       --sysconfdir=/etc/mysql  -- Appends /etc/mysql after ~/ in the my.cnf search patch!
-	#
-	#	--with-debug
-	
-	# TODO fix these build problems: some files don't get copied to builddir
-	cp -rf storage/ndb/ndbapi-examples builddir/storage/ndb
-	# TODO --end--
+		-DWITH_BUNDLED_MEMCACHED=Off \
+		\
+		-DWITH_EMBEDDED_SERVER=On \
+		-DHAVE_EMBEDDED_PRIVILEGE_CONTROL=On \
+		    ..'
 	
 	touch $@
 
@@ -138,6 +136,10 @@ build: build-stamp build-stamp-pic
 build-stamp: configure
 	@echo "RULES.$@"
 	dh_testdir
+	
+	[ -f $(EXPORTED_SOURCE_TARBALL) ] || tar -zcf $(EXPORTED_SOURCE_TARBALL) \
+	--exclude=debian . \
+	--transform="s,^\./,mysql-cluster-7.2/,"
 
 	cd $(builddir) && $(MAKE) $(MAKE_J)
 
@@ -161,21 +163,20 @@ MAKE_PIC = cd $(builddir) && $(MAKE) $(MAKE_J)
 build-stamp-pic: configure-pic
 	@echo "RULES.$@"
 	# Build libmysqld dependencies
-	$(MAKE_PIC) -C include
-	$(MAKE_PIC) -C sql link_sources
-	$(MAKE_PIC) -C libmysql link_sources
-	$(MAKE_PIC) -C strings
-	$(MAKE_PIC) -C regex
-	$(MAKE_PIC) -C mysys
-	$(MAKE_PIC) -C dbug
-	$(MAKE_PIC) -C vio
-	$(MAKE_PIC) -C storage
-	$(MAKE_PIC) -C extra/yassl
-	$(MAKE_PIC) -C cmd-line-utils
-	$(MAKE_PIC) -C sql lex_hash.h
+	#(MAKE_PIC) -C include
+	#(MAKE_PIC) -C sql link_sources
+	#(MAKE_PIC) -C libmysql link_sources
+	#(MAKE_PIC) -C strings
+	#(MAKE_PIC) -C regex
+	#(MAKE_PIC) -C mysys
+	#(MAKE_PIC) -C dbug
+	#(MAKE_PIC) -C vio
+	#(MAKE_PIC) -C storage
+	#(MAKE_PIC) -C extra/yassl
+	#(MAKE_PIC) -C cmd-line-utils
+	#(MAKE_PIC) -C sql lex_hash.h
+	$(MAKE_PIC) -C scripts
 	# Build libmysqld itself
-	echo NOW MAKE libmysqld
-	exit
 	$(MAKE_PIC) -C libmysqld
 	
 	touch $@
@@ -196,6 +197,7 @@ clean-patched:
 	rm -rf $(BUILDDIR) $(BUILDDIR_PIC)
 
 	#debconf-updatepo
+	rm -f $(EXPORTED_SOURCE_TARBALL)
 	dh_clean -v
 
 
@@ -207,13 +209,19 @@ install install-pic: build
 	dh_prep
 	dh_installdirs
 
+	# some self written manpages which hopefully
+	# gets overwritten sooner or later with upstreams
+	mkdir -p $(TMP)/usr/share/man/man1/
+	mkdir -p $(TMP)/usr/share/man/man8/
+	cp debian/additions/*.1 $(TMP)/usr/share/man/man1/
+
 	# mysqld_safe config
 	mkdir -p $(TMP)/etc/mysql/conf.d/
 	cp debian/additions/mysqld_safe_syslog.cnf $(TMP)/etc/mysql/conf.d/
 
 	# make install (trailing slash needed for innobase)
 	cd $(builddir) && $(MAKE) install DESTDIR=$(TMP)/
-	
+		
 	# After installing, remove rpath to make lintian happy.
 	set +e; \
 	find ./debian/tmp/ -type f -print0 \
@@ -223,69 +231,80 @@ install install-pic: build
 		| xargs --no-run-if-empty chrpath -d; \
 	set -e
 
-	# libmysqlclusterclient16: move shared libraries (but not the rest like libheap.a & co)
-	mv $(TMP)/usr/lib/mysql/libmysqlclusterclient* $(TMP)/usr/lib
-	sed -i -e 's#/usr/lib/mysql#/usr/lib#' $(TMP)/usr/lib/libmysqlclusterclient.la
-	sed -i -e 's#/usr/lib/mysql#/usr/lib#' $(TMP)/usr/lib/libmysqlclusterclient_r.la
+	# libmysqlclient
 	# Check if our beloved versioned symbols are really there
-	if [ "`objdump -T $(TMP)/usr/lib/libmysqlclusterclient.so.16.0.0 | grep -c libmysqlclusterclient_16`" -lt 500 ]; then \
-	  echo "ERROR: versioned symbols are absent"; \
-	  exit 1; \
-	fi     
+	#if [ "`objdump -T $(TMP)/usr/lib/libmysqlclient.so.18.0.0 | grep -c libmysqlclient_18`" -lt 500 ]; then \
+	#  echo "ERROR: versioned symbols are absent"; \
+	#  exit 1; \
+	#fi
 
-	# libmysqlclusterclient-dev: forgotten header file since 3.23.25?
-	cp $(BUILDDIR)/include/my_config.h $(TMP)/usr/include/mysql/
-	cp include/my_dir.h $(TMP)/usr/include/mysql/
+	# libmysqlclient-dev
+
+	# libndbclient
+	# Check if our beloved versioned symbols are really there
+	#if [ "`objdump -T $(TMP)/usr/lib/libndbclient.so.6.0.0 | grep -c libndbclient_6`" -lt 500 ]; then \
+	#  echo "ERROR: versioned symbols are absent"; \
+	#  exit 1; \
+	#fi     
 
 	# libndbclient-dev
 
-	# libndbclient: move shared libraries (but not the rest like libheap.a & co)
-	mv $(TMP)/usr/lib/mysql/libndbclient* $(TMP)/usr/lib
-	perl -pi -e 's#/usr/lib/mysql#/usr/lib#' $(TMP)/usr/lib/libndbclient.la
-	# Check if our beloved versioned symbols are really there
-	if [ "`objdump -T $(TMP)/usr/lib/libndbclient.so.4.0.0 | grep -c libndbclient_4`" -lt 500 ]; then \
-	  echo "ERROR: versioned symbols are absent"; \
-	  exit 1; \
-	fi     
+	# libmysqld-dev
+	# install libmysqld built with -fPIC
+	install -d -m 0755 -o root -g root $(TMP)/usr/lib/mysql
+	install -m 0644 -o root -g root $(BUILDDIR_PIC)/libmysqld/libmysqld.a $(TMP)/usr/lib/mysql/libmysqld_pic.a
+	# mysql_config won't report the -fPIC, so give libmysqld-pic users a way to get their flags
+	install -m 0755 -o root -g root $(BUILDDIR_PIC)/scripts/mysql_config $(TMP)/usr/bin/mysql_config_pic
 
-	# libndbclient-dev
-##	cp $(BUILDDIR)/include/my_config.h $(TMP)/usr/include/mysql/
-##	cp include/my_dir.h $(TMP)/usr/include/mysql/
+	# mysql-common: We now provide our own config file.
+	install -d $(TMP)/etc/mysql
+	install -m 0644 debian/additions/my.cnf $(TMP)/etc/mysql/my.cnf
 
-##	# mysql-common: We now provide our own config file.
-##	install -d $(TMP)/etc/mysql
-##	install -m 0644 debian/additions/my.cnf $(TMP)/etc/mysql/my.cnf
+	# mysql-client
+	install -m 0755 debian/additions/mysqlreport $(TMP)/usr/bin/
+	install -m 0755 debian/additions/innotop/innotop $(TMP)/usr/bin/
+	install -m 0644 debian/additions/innotop/innotop.1 $(TMP)/usr/share/man/man1/
 
 	# mysql-cluster-client
 
+	# mysql-cluster-testsuite
+	mkdir -p $(TMP)/usr/lib/mysql-testsuite
+	cp -rp $(TMP)/usr/share/mysql-test/* $(TMP)/usr/lib/mysql-testsuite
+
 	# mysql-cluster-server-mgmt
+	mkdir -p $(TMP)/usr/share/doc/mysql-cluster-server-mgmt-7.2/examples
+	nm -n $(BUILDDIR)/storage/ndb/src/mgmsrv/ndb_mgmd | gzip -9 > $(TMP)/usr/share/doc/mysql-cluster-server-mgmt-7.2/ndb_mgmd.sym.gz
 
 	# mysql-cluster-server-data
+	mkdir -p $(TMP)/usr/share/doc/mysql-cluster-server-data-7.2/examples
+	nm -n $(BUILDDIR)/storage/ndb/src/kernel/ndbmtd | gzip -9 > $(TMP)/usr/share/doc/mysql-cluster-server-data-7.2/ndbmtd.sym.gz
+	nm -n $(BUILDDIR)/storage/ndb/src/kernel/ndbd | gzip -9 > $(TMP)/usr/share/doc/mysql-cluster-server-data-7.2/ndbd.sym.gz
 
 	# mysql-cluster-server-sql
-	install -m 0755 $(BUILDDIR)/scripts/mysqld_safe $(TMP)/usr/bin/mysqld_safe
-	mkdir -p $(TMP)/usr/share/doc/mysql-cluster-server-sql-7.1/examples
-	mv $(TMP)/usr/share/mysql/*cnf 	    $(TMP)/usr/share/doc/mysql-cluster-server-sql-7.1/examples/
+	mkdir -p $(TMP)/usr/share/doc/mysql-cluster-server-sql-7.2/examples
+	mv $(TMP)/usr/share/mysql/*cnf $(TMP)/usr/share/doc/mysql-cluster-server-sql-7.2/examples/
 	rm -vf $(TMP)/usr/share/mysql/mi_test_all* \
 	       $(TMP)/usr/share/mysql/mysql-log-rotate \
 	       $(TMP)/usr/share/mysql/mysql.server \
 	       $(TMP)/usr/share/mysql/binary-configure
-	nm -n $(BUILDDIR)/sql/mysqld |gzip -9 > $(TMP)/usr/share/doc/mysql-cluster-server-sql-7.1/mysqld.sym.gz
+	nm -n $(BUILDDIR)/sql/mysqld | gzip -9 > $(TMP)/usr/share/doc/mysql-cluster-server-sql-7.2/mysqld.sym.gz
 	install -m 0755 debian/additions/echo_stderr $(TMP)/usr/share/mysql/
 	install -m 0755 debian/additions/debian-start $(TMP)/etc/mysql/
 	install -m 0755 debian/additions/debian-start.inc.sh $(TMP)/usr/share/mysql/
-##	# lintian overrides
-##	mkdir -p $(TMP)/usr/share/lintian/overrides/
-##	cp debian/mysql-common.lintian-overrides     $(TMP)/usr/share/lintian/overrides/mysql-common
-##	cp debian/mysql-server-5.1.lintian-overrides $(TMP)/usr/share/lintian/overrides/mysql-server-5.1
-##	cp debian/mysql-client-5.1.lintian-overrides $(TMP)/usr/share/lintian/overrides/mysql-client-5.1
+	# lintian overrides
+	#mkdir -p $(TMP)/usr/share/lintian/overrides/
+	#cp debian/mysql-common.lintian-overrides     $(TMP)/usr/share/lintian/overrides/mysql-common
+	#cp debian/mysql-server-5.5.lintian-overrides $(TMP)/usr/share/lintian/overrides/mysql-server-5.5
+	#cp debian/mysql-client-5.5.lintian-overrides $(TMP)/usr/share/lintian/overrides/mysql-client-5.5
 
 	# For 5.0 -> 5.1 transition
-##	d=$(TMP)/usr/share/mysql-common/internal-use-only/; \
-##	mkdir -p $$d; \
-##	cp debian/mysql-server-5.1.mysql.init $$d/_etc_init.d_mysql; \
-##	cp debian/mysql-server-5.1.mysql-cluster-server-sql.logrotate $$d/_etc_logrotate.d_mysql-cluster-server-sql; \
-	cp debian/additions/debian-start $$d/_etc_mysql_debian-start;
+	#d=$(TMP)/usr/share/mysql-common/internal-use-only/; \
+	#mkdir -p $$d; \
+	#cp debian/mysql-server-5.1.mysql.init $$d/_etc_init.d_mysql; \
+	#cp debian/mysql-server-5.1.mysql-cluster-server-sql.logrotate $$d/_etc_logrotate.d_mysql-cluster-server-sql; \
+	#cp debian/additions/debian-start $$d/_etc_mysql_debian-start;
+
+	install -D -m 0644 $(EXPORTED_SOURCE_TARBALL) $(TMP)/usr/src/mysql/`basename $(EXPORTED_SOURCE_TARBALL)`
 
 	dh_movefiles
 	
@@ -338,10 +357,13 @@ binary-arch: build install
 	dh_compress -a
 	dh_fixperms -a
 	#dh_makeshlibs -a
-	dh_makeshlibs -plibmysqlclusterclient16 -V'libmysqlclusterclient16 (>= 7.1.15a-0.1)'
+	dh_makeshlibs -plibmysqlclient18 -V'libmysqlclient18 (>= 7.2.4-0.1)'
+	dh_makeshlibs -plibndbclient6 -V'libndbclient6 (>= 7.2.4-0.1)'
 	dh_installdeb -a
 	dh_perl -a
-	dh_shlibdeps -a -l debian/libmysqlclusterclient16/usr/lib -L libmysqlclusterclient16
+	#dh_shlibdeps -a -l debian/libmysqlclient18/usr/lib -L libmysqlclient18
+	#dh_shlibdeps -a -l debian/libndbclient6/usr/lib -L libndbclient6
+	dh_shlibdeps -a
 	dh_gencontrol -a
 	dh_md5sums -a
 	dh_builddeb -a
